apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: release-t 
  janus-idp.io/tekton: release-t
  backstage.io/kubernetes-id: release-t
  backstage.io/kubernetes-namespace: release-t 
  app.kubernetes.io/part-of: release-t
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  