apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: release-t
  janus-idp.io/tekton: release-t
  backstage.io/kubernetes-id: release-t
  backstage.io/kubernetes-namespace: release-t 
  app.kubernetes.io/part-of: release-t
resources: 
- deployment.yaml
- route.yaml
- service.yaml
