apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: release-t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-t 
  name: release-t
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: release-t
    weight: 100 
